### ISSUE TITLE
Navigate through future years

### ISSUE THREAD

**Issue by rubenstolk** [pkaske/pk-datepicker#5]
Hi, related to #4 we also need a way to browse to years in the future, currently you allow 100 years in the past, I guess we could make the number of years in past and future configurable through properties?

**Comment by trading-peter** [comment]
Yeah, that sounds good. Properties would be the way to go.
My problem right now is that I have to keep my working time in front of a screen to a minimum because of health issues. As it looks right now it will take about 2 weeks till I can implement that. If you need it sooner, fell free to submit a pr. Shouldn't be hard to implement.

**Comment by trading-peter** [comment]
Have a look at the newest release. I added the date-fwd and date-back properties. Not much more but I had to make it quick. Hope it helps :)

**Comment by rubenstolk** [comment]
Great! Will have a look tomorrow and let you know if there is any issue.

**Comment by rubenstolk** [comment]
Yep works like a charm. Two things you might want to consider:
- [ ] Update the documentation / component page
- [ ] There is a style variable for `--pk-datepicker-yearlist-item-current` however, that one applies only to the current year but not the currently selected year, I think the latter might make more sense (or perhaps have two variables)

**Comment by trading-peter** [comment]
Update in 2.3.3
- [x] Update the documentation / component page (at least for the most part)
- [x] `--pk-datepicker-yearlist-item-selected` can now be used to style the selected month

**Comment by rubenstolk** [comment]
Nice!
